
base_url = "https://docs.now-it.works"

compile_sass = true
build_search_index = true
theme = "easydocs"

[markdown]
highlight_code = true

[slugify]
paths = "off"

[search]
include_title = true
include_description = true
include_path = false
include_content = true

[extra]
# Put all your custom variables here
