
base_url = "/"

compile_sass = false
build_search_index = false
theme = "easydocs"

[markdown]
highlight_code = true

[slugify]
paths = "off"

[extra]
module = "Devolutions.PowerShell"
latest = "2024.3.5"
versions = [
    "2024.3.5",
    "2024.3.4",
    "2024.3.3"
]
